# Generated by Django 4.2 on 2024-07-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_members_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='chat_app.members')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='chat_app.members')),
            ],
        ),
    ]
