# Generated by Django 4.2 on 2024-07-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user1',
            new_name='sender',
        ),
    ]
