# Generated by Django 4.2 on 2024-08-06 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_rename_user2_messages_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
