# Generated by Django 4.2 on 2024-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_members_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, help_text='last seen'),
        ),
    ]
